---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: partner
  namespace: tnf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partner
  template:
    metadata:
      labels:
        app: partner
      name: partner
    spec:
      containers:
        - command:
            - tail
            - -f
            - /dev/null
          image: quay.io/testnetworkfunction/cnf-test-partner:latest
          name: partner
          resources:
            limits:
              memory: 1Gi
              cpu: 1
      nodeSelector:
        role: partner
