name: 'Test the `local-test-infra` config'
on: [push, pull_request]
defaults:
  run:
    shell: bash

jobs:
  test-local-test-infra:
    name: 'Test the `local-test-infra` configuration on minikube'
    runs-on: ubuntu-20.04
    env:
      TNF_NAMESPACE: tnf
      PUT_RESOURCE_NAME: test
      TPP_RESOURCE_NAME: partner
      DEFAULT_TIMEOUT: 90s

    steps:
      - uses: actions/checkout@v2

      - name: Start the minikube cluster
        uses: ./.github/actions/start-minikube

      - name: Create `local-test-infra` OpenShift resources
        uses: ./.github/actions/create-local-test-infra-resources

      # Tests for the test pod (PUT)

      - name: '(test pod) Test: Check if ping is installed'
        run: oc exec -i $PUT_RESOURCE_NAME -c $PUT_RESOURCE_NAME -- which ping

      - name: '(test pod) Test: Check if ip is installed'
        run: oc exec -i $PUT_RESOURCE_NAME -c $PUT_RESOURCE_NAME -- which ip

      - name: '(test pod) Test: Check if ssh is installed'
        run: oc exec -i $PUT_RESOURCE_NAME -c $PUT_RESOURCE_NAME -- which ssh

      # Tests for the partner pod (TPP)

      - name: '(partner pod) Test: Check if ping is installed'
        run: oc exec -i $TPP_RESOURCE_NAME -c $TPP_RESOURCE_NAME -- which ping

      - name: '(partner pod) Test: Check if ip is installed'
        run: oc exec -i $TPP_RESOURCE_NAME -c $TPP_RESOURCE_NAME -- which ip

      - name: '(partner pod) Test: Check if ssh is installed'
        run: oc exec -i $TPP_RESOURCE_NAME -c $TPP_RESOURCE_NAME -- which ssh

      # Cleanup

      - name: Delete OpenShift resources
        run: make clean

      - name: 'Test: Check if `make clean` removed all TNF pods'
        run: '[[ "$(oc get pods -o name | wc -l)" -eq "0" ]]'
