name: 'Push the `cnf-test-partner` image'
on:
  workflow_run:
    workflows: ['Test the `cnf-test-partner` image']
    types: [completed]
    branches:
      - main
env:
  REGISTRY: quay.io
  IMAGE_NAME: mkochanowski/cnf-test-partner
  IMAGE_TAG: latest
  IMAGE_CONTAINER_FILE_PATH: test-partner/Dockerfile

jobs:
  push-cnf-test-partner-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: 'Push the new `cnf-test-partner` image to Quay.io'
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          # always build container images from the default branch
          ref: main

      - name: Authenticate against Quay.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          # Use a Robot Account to authenticate against Quay.io
          # https://docs.quay.io/glossary/robot-accounts.html
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: 'Build and push the new `cnf-test-partner` image'
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ env.IMAGE_CONTAINER_FILE_PATH }}
          tags: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
